#!/bin/sh
. /opt/farm/scripts/init

# Binaries downloaded from
# https://www.enterprisedb.com/download-postgresql-binaries

if [ "$OSVER" = "debian-buster" ]; then
	pgver="10.10"
else
	pgver="10.7-1"
fi

arch=`/opt/farm/ext/system/detect-architecture.sh`
path=/opt/farm/ext/binary-pgdump/bin/postgresql-$pgver/linux.$arch

if [ ! -d $path ] || ! grep -qFx $OSVER /opt/farm/ext/binary-pgdump/config/below10.conf; then
	/usr/bin/pg_dump "$@"
else
	LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib  "$path/bin/pg_dump" "$@"
fi
